version: '3.8'

services:
  app-5001:
    build: .
    ports:
      - "5001:5001"
    command: go run main.go node -n 5001

  app-5002:
    build: .
    ports:
      - "5002:5002"
    command: go run main.go node -n 5002

  app-5003:
    build: .
    ports:
      - "5003:5003"
    command: go run main.go wallet -n 5003

  app-5004:
    build: .
    ports:
      - "5004:5004"
    command: go run main.go wallet -n 5004
